name: graph_app
channels:
  - defaults
dependencies:
  - aom=3.12.1=h00a0c3c_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - dav1d=1.2.1=h2bbff1b_0
  - expat=2.7.3=h9214b88_0
  - fontconfig=2.15.0=hd211d86_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.9=py310h03f52e7_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.3.0=h5bd13ec_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-base=3.10.7=py310h26e45b9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=2.1.1=py310h300f80d_0
  - mkl_random=1.3.0=py310ha5e6156_0
  - numexpr=2.14.1=py310h7660c64_0
  - numpy-base=2.2.5=py310h7794460_2
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py310h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - pyparsing=3.2.5=py310haa95532_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py310haa95532_0
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.61.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpickle==4.1.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lxml==6.0.2
      - markupsafe==3.0.3
      - narwhals==2.13.0
      - networkx==3.4.2
      - numpy==2.2.6
      - plotly==6.5.0
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - python-louvain==0.16
      - pyvis==0.3.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - smmap==5.0.2
      - streamlit==1.52.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - watchdog==6.0.0
prefix: C:\Users\HANNAH_SOPHIE\anaconda3\envs\graph_app
